apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-dep
spec:
  selector:
    matchLabels:
      name: test-springboot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        name: test-springboot-k8s
    spec:
      containers:
        - name: test-springboot-k8s
          image: heydie/jenkins-automation:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
spec:
  selector:
    name: test-springboot-k8s
  ports:
    - port: 8085
      targetPort: 8085
  type: NodePort