apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-springboot-app-deployment
spec:
  selector:
    matchLabels:
      name: test-springboot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        name: test-springboot-k8s
    spec:
      containers:
        - name: test-springboot-k8s
          image: heydie/jenkins-automation
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: test-springboot-service
spec:
  selector:
    name: test-springboot-k8s
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort